source 'https://rubygems.org'

# Specify your gem's dependencies in sensit.gemspec
gemspec

gem 'devise'
gem 'sensit_core', :path => "api/core"
gem 'sensit_percolator', :path => "api/percolator"
gem 'sensit_reports', :path => "api/reports"
gem 'sensit_subscriptions', :path => "api/subscriptions"
gem 'sensit_frontend', :path => "frontend"
gem 'sqlite3'